### ISSUE TITLE
Create publisher sample

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#120]
I added `example/SSR-server`  with a working Dockerfile. It's successfully rendering at http://localhost:3001/ssr/?url=http://localhost:3000/image-gallery/&selector=lotus-image-gallery. I want to turn it into a fly.io app. They have a sample [here](https://github.com/fly-apps/puppeteer-js-renderer/). Ideally, it will be the first app I deploy under my new architecture. The flow should be:
1. SPA hosted on Fly.
2. Deploy the current function to render along with the required HTML/CSS files under example.
2. OpenResty + NGINX proxy for URL rewrite (done).
3. Pass in `/images` in the proxy route. The proxy should rewrite to the private fly.io endpoint for the rendering service.  The renderer should be able to serve the corresponding path at localhost. 
4. Test locally before deploying
5. Added bonus, allow a custom selector to be passed in the headers of the request. Make sure it passes through the proxy.

We need to make sure we use the private DNS for the rendering endpoint. Also, make sure we have a pool of puppeteer rendering agents to pick from. I'd like to let the filesystem drive the path resolution if possible. IE `/images` should resolve in the container app to `static/images`. This allows an entire site to be SSR'd used the static serving path for express.

**Comment by doriansmiley** [comment]
Useful links:

1. https://developers.google.com/web/tools/puppeteer/troubleshooting#running_puppeteer_in_docker
2. https://github.com/thomasdondorf/puppeteer-cluster (don't use this, review source and write your own).

**Comment by doriansmiley** [comment]
Implement `debug`

**Comment by dsmileybrainly** [comment]
> Remaining items:
> 
> 1. Implement `debug`
> 2. Look into minification of the HTML with inline CSS and javascript using [this tool](https://www.npmjs.com/package/html-minifier).
> 3. Pooling for puppeteer

Consider an option to inline images. Update the example to publish to [github pages](https://pages.github.com/).
