### ISSUE TITLE
Implement a component that uses CSS custom properties

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#37]
Read: https://www.smashingmagazine.com/2017/04/start-using-css-custom-properties/

Basically javascript exposes two methods to effect custom properties that are used in variable definitions: .getPropertyValue() and .setProperty(). This allows you to effect the value at runtime and have the browser resolve the changes. This is a huge breakthrough that could make the use of callbacks that manually resolve model changes in view components obsolete. I'm not sure it it totally negates model bindings to effect changes int he view, but it might. I assume these custom properties would need to be assigned in the shadow DOM so they don't leak into the global scope. They should still be reachable through javascript but we have to be sure.

**Comment by KipOmaha** [comment]
I'm going to look into this very closely it's something I've wanted to dive into independently, thank you for bringing this enhancement issue up.

**Comment by doriansmiley** [comment]
@KipOmaha no worries, yeah I'm super into the possibilities here. I think it will change how we approach MVW in general. View resolution can be delegated in some respects to the browsers which is really cool. Can't wait to see what you come up with.

**Comment by KipOmaha** [comment]
https://github.com/malyw/css-vars

**Comment by KipOmaha** [comment]
Did you read to the mixin part?

**Comment by KipOmaha** [comment]
A start to some simple rules:

    1. Declare variables at the top of the stylesheet 
    2. Variables declared as numeric values will use the calc() function and percentage 
    -- unit mathematics to account for padding, margins, borders, outlines, and overflow. 
    3. Containers should all be flex or grid types for stand alone application crossover. 
    -- Relatively positioned flex containers work well in my expierence, but it's much more 
    -- diffucult to create absolutely positioned flex containers. Alot of times absolute 
    -- just isn't the way to go cause their is simpler method you can use. Fixed   
    -- positioned elements float on the page where you set them which is fine but 
    -- these elements that are fixed should not be in a containr to avoid z-index 
    -- problems. 
    4. Font Sizes should be encapsulated in media queries 
    5. Company brand colors should all be stored in variables 
    6. Buttons should be place statically VIA margin or padding at least 40-60 pixels away 
    -- from device screen edges, to get better touch responsiveness. 
    -- [In older models the edges are touchier] 
    7. Avoid screen overflows, because it cause glitchy behavior in rendering and kinetic 
    -- scrolling in mobile devices. On IOs from my own expierence it takes a more minimal
    -- aproach to markup and outputs sassiness when you nest in container and set its overflow  
    -- to scroll [Why? I think they don't like your container tag....SHRUG].  
    8. Container menus should fill to the corners of their parent but maintain a padding inside of it. 
    9. Styling by ID is discouraged please use CSS attr query, classes, or css-selectors. 
    10. Animations should be simple and fast, 500ms-1000ms. Their are exceptions, but most professions 
    -- or shoppers don't have the time to watch them. Animations should be complimentary and sensible.

**Comment by KipOmaha** [comment]
So I'm not quite sure about it but decided a list of things to think about while developing components would be good. 

I'll link an article I read for reference
