### ISSUE TITLE
Create an AMP demo

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#50]
Try doing a demo page and see if we can use AMP documents in component skins.

About:
https://www.ampproject.org/learn/about-how/

Amp also has it's own custom elements core:
https://www.ampproject.org/docs/reference/components

From what I am reading you would not include your own custom elements inside an AMP document. Instead, have your components load AMP documents as part of their skin. This thread has some info: https://github.com/ampproject/amphtml/issues/5216. This makes the bulk of the content an AMP document I think as the skin is just a static HTML template. 

Create first AMP page:
https://www.ampproject.org/docs/tutorials/create

Creating responsive pages:
https://www.ampproject.org/docs/guides/responsive/responsive_design

**Comment by doriansmiley** [comment]
I'm not sure this will be doable, need someone to evaluate to see if it makes sense.

**Comment by KipOmaha** [comment]
It doesn't support JS unless its in an iframe with sand-boxing it sounds like.  It sounds more like a frame work that you might plugin a couple of iframed components to me at least.

**Comment by KipOmaha** [comment]
As far as doable it most likely is, but would take a working project of its own to do I think.

**Comment by doriansmiley** [comment]
@KipOmaha yeah I wasn't sure how viable this would be. I know that some people will load AMP pages into their components since AMP can not support non AMP components within an AMP page. It's not super important that we deliver this, but it is good to know how or if Lotus could integrate with AMP. One thing I have noticed with frameworks like AMP is you tend to sacrifice flexibility for performance. This is a lot like the debates surrounding OR mapping tools vs stored procedure API. At some point you have to decide what is more important. Lotus may just fall on the flexibility side of that equation, which is fine. If you think of anything that could promote interoperability go ahead and document it here.

**Comment by KipOmaha** [comment]
```
The <amp-iframeiframe> tag, similar to the traditional HTML version of the <iframe>, allows publishers to add chunks of JavaScript hosted on their own websites, but there are some restrictions. Code inserted into iFrames won’t have acess to all the data that a script inserted directly into a traditional page does. AMP always loading the page’s core content before any <amp-iframeiframe> content in order to keep <amp-iframeiframe>s from slowing down pages. And when AMP pages are hosted on Google’s servers, the pages are pre-rendered, so that they still load quickly.

These workarounds enable more freedom for publishers, but it also means there’s still room for them to serve invasive scripts to readers. Improved performance won’t always mean improved privacy. It also means more of the web will be shaped by Google.
```

**Comment by KipOmaha** [comment]
I am not sure how I feel about this...any thoughts?

**Comment by doriansmiley** [comment]
@KipOmaha so I am really torn on AMP. I'm not a very big fan of anything that is not standards based. The reason is most of the time non standards based technology is almost always replaced by a standards based version. Take Flash for example. This leaves people who invested in the non standard version with a huge refactoring when standards eventually take over. However this takes a very long time to occur. 

Second I do have concerns about Google's strategy regarding what amounts to republication of website content. I know we are talking about an 800ld gorilla, but there are major news organizations and sports leagues who may opt out of AMP due to the fact Google is essentially republishing their content without permission or compensation. It is possible to take a standards based approach to achieve things like parallel script loading, optimization of JavaSCript content, etc that will make you sites load super fast, not AMP fast but perhaps fast enough to allow people opting out of AMP a good enough alternative. 

Regarding iFrame's I hate them and will never use them. There are huge security restrictions, and they perform really poorly. 

With all that said I'm wondering if there is a way to publish component pages after rendition in a way that is AMP friendly. Even if for example all the Javascript code is removed, or perhaps normalized in some way. If we had some kind of CLI or similar tool that would produce AMP friendly pages after everything renders in say a headless browser people could take advantage of AMP caches. There would obviously be some restriction surrounding what kind of behaviors could be successfully exported, and how (mostly inline script I think), but it might  be a better alternative. This essentially allows people to serve their sites with full featured LotusJS components then publish AMP pages with limited functionality for Google's AMP cache. Let me know your thoughts.

**Comment by staramir** [comment]
I don't see the benefit of using AMP as I believe the performance gained by AMP is really due to the restriction set by their standards. If you load an HTML page with no JS using HTTP2, I am pretty sure you would achieve the same performance. How widely adopted is AMP? It wouldn't hurt to create a demo if there is a lot of support and adoption of it but as I see it, I don't think AMP will really be around for long as HTTP2 is becoming the new standard.

**Comment by KipOmaha** [comment]
> With all that said I'm wondering if there is a way to publish component pages after rendition in a way that is AMP friendly.

This I believe goes back to the issue of wanting to maintain an Amp API, for people who want to develop AMP from LotusJS components. If it's what developers and businesses want then I would say that it's worth it. 

You might argue though, that finding work arounds for Amp from Javascript probably goes against good sense, I mean is a workaround part of a real framework? Which yes it could be but the security restrictions are coming from Google, and which ones are they going to implement next and what privacy standards are they going to enfore? 

For developers using lotusJS this may be something that they can do on their end of development, which may be a bummer but unless Google wants to be more compliant with standards on there server I don't think that their will be a real good catch all process for implementing somebodies AMP page from JS. If we wanted to support it at all, maybe having a, `Getting started with LotusJS and AMP` document outlining a method for combining the two would be a better resource to have?  It could also be user created and crafted in part also. That way people using it can collaborate on best practices concerning Lotus and Amp builds

Packaging it with LotusJS may not even be a real catch all for people on LotusJS or AMP, too.

**Comment by doriansmiley** [comment]
@KipOmaha @staramir Amir I agree. I think we should just back standards and close this issue. AMP is going to be pretty widely adopted I think but probably for a short period of time. Let's leave it to the community to drive this one as Steve suggested. We can revisit this if we get requests and build up some documentation with the suggested approaches (per Steve's recommendation), but perhaps not building anything concrete until there is demand to do so. For now let's just focus on x-tag v2 and improving Lotus's support for x-tag features.
