### ISSUE TITLE
Implement suggestions from Steve

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#56]
* ~~Create docs section for LotusJS.org using type doc~~
* ~~Implement Pretty Print for code blocks~~
* ~~Enable Wiki in GitHub repo. Now public~~
* ~~Set up chatroom~~

**Comment by KipOmaha** [comment]
@doriansmiley, I'll see what I can do this week.

**Comment by doriansmiley** [comment]
Documentation should include the following sections:
* Overview (include major concepts such and the Lotus context)
* Intall
* Your First Component
* Collection and Item Views
* Built In Components
* Creating Advanced Components
* Core API
* Contribute
* Monetize

**Comment by doriansmiley** [comment]
I've started the new documentation sections. I've gotten similar feedback from developers regarding the need for better documentation and I'll make it my priority for the next couple weeks.
