### ISSUE TITLE
Look into an analyzer for webcomponents.org

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#59]
I'd like to be able to publish lotus components to webcomponents.org and get the same level of analysis of the component API as Polymer. The publication guide is here: https://www.webcomponents.org/publish . It states:

````
How do I add API documentation?

Currently, each repository is processed using Polymer/polymer-analyzer. Want to add an analyzer for your library? Chat to us on Gitter.

The documentation for your element is drawn from the README.md file on its GitHub repository. To make sure people can easily use your element, it's good practice to include:

A brief summary of what your element does
System requirements for end-users displaying your element in a web browser
Attributes of your element and possible values
A code sample showing how to include and use your element in an HTML page
For Polymer elements, see "Document your elements" for more information.
````

The Polymer analyzer is here: https://github.com/Polymer/polymer-analyzer

**Comment by KipOmaha** [comment]
I was thinking of the same thing. It's a good idea but it's hard to implement in a practical way, at least on GitHub.  

I don't know, I was thinking of creating a form that would help you create your package.json and bower.json, as well as help package your assets too.
