### ISSUE TITLE
.gitignore node_modules?

### ISSUE THREAD

**Issue by KipOmaha** [doriansmiley/lotusJS#60]
Suggest including node_module dependencies. (ie: lavenderjs and x-tag) so that people can run the examples without npm installing.

**Comment by doriansmiley** [comment]
@KipOmaha the example readme should include instructions on running npm install. We never check in node_modules. This is generally best practice. We could update the HTML files with instruction though. I could include a section at the top entitled "Running this example".

**Comment by KipOmaha** [comment]
Cool, I didn't see that in the example readme should have checked for the readme in the example. 
I figured as much though. I will put the node_modules on the build I have going on though, because I'm just developing it. I will make sure that they get put back on the `.gitignore` list.  

Thanks @doriansmiley

**Comment by KipOmaha** [comment]
Maybe we could consolidate all the readme.md files into a single section with instruction for the builds if they are all the same. 

It would be easier to maintain one set of instructions for examples and would reduce the size of the example directory.

**Comment by doriansmiley** [comment]
I keep multiple due to the fact we never really know where the user will land when they enter the example section of the repo. I like having the duplicates to they are sure to see it.
