### ISSUE TITLE
Revising and editing new button example

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#61]
Anything you would like to add to the button example while I'm playing in the code.  

~ ChangeLog
1. Added pretty print
2. Cleaned up the alignment on the code example

**Comment by doriansmiley** [comment]
if you want to and have time try and improve the description. Also you could create another example using a subclass that adds skin parts for example. One thing I found was that our developers here at SPI did not understand the use of selectors in your components was an anti pattern. They did not understnad that if you want to add behaviors to new elements is a subclass you have to define a new skin part in your subclass's override of `defineSkinParts`, then attach event handlers in the override of `onSkinPartAdded`. I want to include examples of this so if you are game that would be cool.

**Comment by KipOmaha** [comment]
I will have a pull request soon with some updates by the end of the weekend, I will tack another example to the end of it to if I have time, if I don't finish the example I will add another file `button-example-dev.js`.

**Comment by KipOmaha** [comment]
Nice...I just did some initial tests of the example request you wanted. LotusJS definitely has some potential.

**Comment by doriansmiley** [comment]
@KipOmaha that's great to hear. looking forward to the pull request.
