### ISSUE TITLE
x-tag v2

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#62]
would you mind a pull request for a build involving a v2 custom elements LotusJS? 

The version of x-tags v2 is off branch though, but I'm looking for feedback and it would be very helpful for v2.

**Comment by doriansmiley** [comment]
I think you should create a feature branch and test it there. We do have some unit tests you can run (just execute npm test) in addition to performing usability testing under the example directory. If everything passes then for sure issue a pull request. Would really like to get updated to the latest x-tag ASAP.

**Comment by doriansmiley** [comment]
@KipOmaha let me know if you want help on this

**Comment by KipOmaha** [comment]
https://github.com/x-tag/core/tree/v2  <= link to v2 branch in the repo

**Comment by KipOmaha** [comment]
When would it be best to start collaborating on this?

**Comment by doriansmiley** [comment]
@KipOmaha I'd like to start today. If you've already created a feature branch let me know and I'll work in that branch. If not I'll create one and post the branch here.

**Comment by KipOmaha** [comment]
I haven't created a branch yet @doriansmiley

**Comment by doriansmiley** [comment]
@KipOmaha not yet, won't get back on this until around 5PM PST. If you want to create a branch before then just post it here.

**Comment by KipOmaha** [comment]
ok

**Comment by KipOmaha** [comment]
I am going to put lotusJS on my dashboard.  The dashboard isn't done yet, but I think it will do for some testing.

**Comment by KipOmaha** [comment]
sorry didn't mean to close this issue

**Comment by doriansmiley** [comment]
@KipOmaha sounds good. Not sure how your dashboard is created but if it is pure Javascript you can see an example of a component that is build in pure Javascript here: https://github.com/doriansmiley/lotusJS-MWV/blob/master/example/sampleApp/js/view/PageNumberDisplay.js . It is totally fine to use LotusJS to create custom components outside of TypeScript. I plan to include some more Javascript examples so maybe this is a good start.

**Comment by KipOmaha** [comment]
kool, it uses javascript.  I've been looking at the typescript, in the examples and how it works with the Javascript.  It's interesting how it's mapped out, did you get a chance to look at v2?

**Comment by doriansmiley** [comment]
@KipOmaha I start looking at V2 last night. Going to take a deeper look tonight and attempt to run tests against the build. One thing I am having a hard time tracking down are release notes, or a summary of the issues that were added to this release.

**Comment by KipOmaha** [comment]
There are jasmine tests that you can take a look at.

**Comment by KipOmaha** [comment]
There docs in the => https://github.com/KipOmaha/x-tag-setup/tree/master/pkgs/docs directory

**Comment by KipOmaha** [comment]
I'm pushing lotusJS to the build

**Comment by KipOmaha** [comment]
The last commit was for an issue involving a recursion error occurring when you used an auto rendering feature of the library.  I also noticed that camel casing didn't work for me, but I put a shim into the build to fix it real quick.  

Also the commit that fixed the recursion error causes the ability to re-render the element to cause an error.

**Comment by doriansmiley** [comment]
@KipOmaha I started testing against x-tag v2 and the first issue I found was with the register function. It looks like a breaking change was introduced in v2 with that method. The old method was implemented as follows:
````
register: function (name, options) {
//full code ommited
}
````
The new method is implemented as follows:
````
,
    register (name, klass) {
      customElements.define(name, klass);
    }
````
Where customElements is an instance of `CustomElementRegistry` or the pollyfill created by x-tag. The define method's signature is defined as follows: `customElements.define(name, constructor, options);`. So in the new `register` the second parameter is a constructor and not an options object that exposes `lifecycle` and `prototype` properties.

We'll have to refactor lotus's component map to adjust for this. Ideally x-tag would not introduce a breaking change like this. I think it would have been better to moved calls to `CustomElementRegistry` under the current `register` method allowing existing code to still pass options as the second param this the call to `register`. 

Another issue that I having is where the source for `x-tag-polyfilled.js` is. Any ideas?

Doe x-tag V2 still require `x-tag/lib/webcomponents.js` or are those files included now in the plugins directory?

**Comment by KipOmaha** [comment]
Sorry I didn't see this in the issues. It's using custom-elements.js and doesn't use the shadow dom.

**Comment by KipOmaha** [comment]
I was thinking of adding the shadow dom files to see about compat. would this be needed?

**Comment by KipOmaha** [comment]
@doriansmiley,

I'm going to try out,  
```
// ***** XTAGELEMENT.BUILDER()
xtag.builder = function build(opts) {
	let _bd = null,
             _bds = xtag.builds,
             klass = null;
	if(!opts) { return createClass(); };

	if( !_bds[opts.name] ) {
		klass = _bds[opts.name] = opts.update;
		klass = _bds[opts.name].update();
	}
	else {
		klass = _bds[opts.name].update();
	};
	return klass;
}
var myCustomBuild = xtag.builder( {
  update: function(){
    // Gather resources like webcomponents or shadowdom
    // Your Custom definition for xtag v2 [Bring in the v1 API that is needed]
  }
} )
```  

Anybody like this idea for custom-element packages. The idea is to create the necessary xtag's object for that particular web page. 

Should I test it on v1 so that we can build xtag v1 into v2 instead of vice versa?

**Comment by KipOmaha** [comment]
I would have to change a couple lines to make it work with v1 though
