### ISSUE TITLE
dashboard example

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#63]
~ x-tag v2 dashboard

Note:  V2 version is off branch.

Would like to provide a dashboard UI for examples. It would also be a great resource to have for the LotusJS project because it's written in x-tag v2 and also could be used to do some initial testing for v2 compatibility.

### Issue:  
Need testing for v2. It's almost complete and I need feedback on the design/arch for the build and components that are in process of being updated to v2.

V2 component updates and additions will include:  
`x-tabbox` 
`x-display` 
`x-menu` 
`x-item` 
`x-toggle`  

Question:  How should the plugins for the dashboard repo for v2 beta be organized to create an intuitive build for re-usability?  

Question: I feel that v2 is a very reusable library but requires a little bit of work given that, how can LotusJS leverage the new v2 version to create a more powerful API when it does come into the full release?  

Question: I'm a LotusJS noob, forgive me if I get this wrong.  Lotus here is creating an instance of an element that inherits the LotusJS API and x-tags adds it's lifecycle API? If so we could leverage x-tags V2 in so many more ways and think that it should be looked at more closely.  Please let me know if their are requests for an x-tag v2 lifecycle extension.
```
var context = (function( xtag ){
  var context = new Lotus.Context(new Lavender.Config);

  context.componentMap.mapComponent('x-lotus-button', Lotus.LotusHTMLElement.prototype, Lotus.Button, xtag);

  context.componentMap.mapComponent('x-lotus-button2', Lotus.LotusHTMLElement.prototype, Lotus.Button, xtag);

            return context;
        }( xtag ));
```
> NOTE: V2 Master branch is at least 90% done. The version on this build is of course at a different point.

~ Thanks and Regards Steve.

**Comment by doriansmiley** [comment]
@KipOmaha 

1. I'm not sure on the organization. I'll have to get more familar with the repo. Where is the dashboard for v2 located?
2. I need to learn more about x-tag v2. Are there release docs yet so I can learn more about what features have been added?
3. That is correct, x-tag adds the pollyfills for shadow DOM, creates the custom element definition, and registers the lifecycle events required to trigger calls to the component's create and destroy methods. The source code for the component map is under the context package. Adding more support for x-tag v2 features is something I am most excited about working on. Let me know what ideas you have already and where I can learn more about the new features in v2.

**Comment by KipOmaha** [comment]
I  did have a setup on a repo but its currently down. I will get it running again soon. I will keep you informed.

**Comment by KipOmaha** [comment]
and here is the link to the repo branch. => https://github.com/x-tag/core/tree/v2
