### ISSUE TITLE
api reference glossary

### ISSUE THREAD

**Issue by KipOmaha** [doriansmiley/lotusJS#65]
Start an API reference library.
  Suggestion: Start it on the gh-repo wiki for contributors for now.
  Reason: For quick referencing of parts of the API

**Comment by doriansmiley** [comment]
@KipOmaha I will for sure be creating API docs from TypeScript. However this will probably be an ongoing support issue for some time as the code will have to be improved with comments to include things like code sample.

**Comment by doriansmiley** [comment]
@KipOmaha I plan to use [TypeDoc](https://www.npmjs.com/package/typedoc) to generate the API docs. I can link to it from the Wiki but will probably publish on lotusjs.org. TypeDoc seems to be the most widely supported doc tool for TypeScript.

**Comment by doriansmiley** [comment]
I've implemented typedoc using the typedoc webpack plugin. Full API docs are generated now as part of the build process. I will have these published to the website under the new documentation sections. You can download the latest from https://www.dropbox.com/s/18x8m2ktaiwkrp0/docs.zip?dl=0
