### ISSUE TITLE
New component ideas

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#67]
Would interesting to see what components could be created using the following API's:

https://developers.google.com/web/fundamentals/primers/service-workers/
https://workboxjs.org/
https://developers.google.com/web/updates/2016/07/payment-request
https://developer.chrome.com/apps/mediaGalleries
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

A really cool component would be one that could take clipboard data and save it as a file on S3. This is similar to comment boxes on Pivotal. So the user cloud copy an image, file, etc, and when they past in the component it will save the file on S3 and show a preview.

**Comment by KipOmaha** [comment]
A custom component that utilizes modern browser indexedDB as well as service-workers would be great. I call the one I'm working on for indexedDB x-extension.  I thought of it as way for web applications to implement a UX for the front-end.

CSS_Grid_Layout,  working on similar CSS.  But haven't thought of componentizing it with custom elements. It could be done, quite simply. What type of behaviors did you want to give it and what type of element would it be, i.e. containers or buttons?

Media Stream goes along with a different API I'm working on for an animator. That's built on php, python[wip], and html/javascript.  At the moment I'm working on the UX for this animator and it's framework.

**Comment by doriansmiley** [comment]
@KipOmaha yeah service worker is really cool. I'm learning the API at the moment and looking at workbox as well. Any web components that implements the API would be really cool. 

For CSS Grid I was thinking there might be a way to combine CSS vars with component attributes so you could pass in the grid parameters in the component's `data-attribute-*`. I'm not sure how it would work though and if x-tag would properly encapsulate css vars in the shadow DOM polyfill, or if CSS vars are properly encapsulated in native shadow DOM.

So as part of LotusJS we plan to build a component exchange where you can sell components. Our philosophy is that the most powerful and valuable components should be what we call "SaaS Components". These components should use signed requests to perform standard oAuth workflows to authenticate users using an access token that is passed into the component at runtime using `data-attribute-*` or component mediators. A media player based on Media Stream would be really cool. There are a lot of them out there now, but I think this it is a great example for a "SaaS Component". However this does require a robust backend that could support some type of SaaS model such as a service/platform offered through AWS Marketplace. A better option mught be to develop a SaaS component that supports popular platforms such as Vimeo what wrap their existing API and perhaps offer additional features for managing playlists, etc.

**Comment by KipOmaha** [comment]
So you want to work on UX and standards I take it?  At least in a nutshell?

**Comment by KipOmaha** [comment]
Well at least standards concerning security features?

**Comment by KipOmaha** [comment]
The only problem with that is, what are your standards for allowed components. If you could elaborate on that it would be helpful.

**Comment by doriansmiley** [comment]
@KipOmaha the idea with "SaaS components" is simply using a flow similar to oAutth's authorization code grant flow where by the surrounding web application generates an access token using a key pair. This access token is then passed into the web component tag using a server side scripting language similar to:
````
<x-my-component data-attribute-auth-token="token-created-by-server"/>
````
At this point the custom element can now pass the supplied auth token in requests. This opens up the possibility of innumerable custom elements that are sold as part of a service agreement. Examples that come to mind are things like:

* Cloudinary elements for image breakpoints
* Streaming media elements that are coupled with a service like Akamai or Vimeo
* Graphics elements for manipulating images using services like AWS Image Recognition and ImageMagick implementations.

These are just examples, but it allows custom elements to interact with backend services using a standard oAuth flow, and to have those service interaction baked into the component. That's where things like service worker and indexedDB come in as these type of "SaaS components" have to be essentially sandboxed applications. In my opinion web components that can expose functionalities of pay services with a framework like LotusJS would be very easy to customize and very valuable to developers that truly want a plug and play experience.

But I'm up for anything cool. I just want to build up a library of cool stuff that people will use. Honestly some of the most used components are data grids and lists. I also think a grid layout component that uses CSS variables would be really cool.

**Comment by KipOmaha** [comment]
Your last statement hits home, a lot of my psuedos for v2 are going to be list style psuedos to help in turn `data` into a readable format.  One of the reasons I was interested in your component system was cause of the monetization system you want to develop.  

Which I think would help facilitate people to new standards, for a while I was very torn on the upgrade to v2 and a custom-elements implementation library for my projects. That being said after using it and seeing the difference it was worth it. Classes/Custom-elements works great and is so very intuitive. 

Even with the fact that it does not encapsulate the v1 API, it still could be extended using the v2 API.

**Comment by KipOmaha** [comment]
It's very interesting to me the way you use `type script` to help facilitate a framework that is friendly to javascript and graphics, VIA LotusJS. For my personal use I would use it as a development environment as long as it's maintained as an open source project.
