### ISSUE TITLE
Review best practice for out of box performance

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#68]
* Service Worker: https://developers.google.com/web/fundamentals/primers/service-workers/
* Cache: https://developer.mozilla.org/en-US/docs/Web/API/Cache
* PRPL pattern: https://developers.google.com/web/fundamentals/performance/prpl-pattern/
* CloudFront Cache headers: https://github.com/doriansmiley/lotusJS-Web/issues/1
* Consider separating the following core UI components into their own repos: 

Form (includes the data driven form component)
Form Elements (includes all form elements including file upload components)
Image (includes the Image and Image gallery components)

This will improve the load times for sites that do not want the lotus core and break up code. Consider also a bundle that still includes everything for people that do want all the core components.

* Be sure to evaluate each example in https://www.webpagetest.org/ez .
* Explore the possibility of using Angular's AoT compiler: https://angular.io/guide/aot-compiler
* https://www.npmjs.com/package/webpack-bundle-analyzer
* https://developers.google.com/web/tools/lighthouse/
* https://webpack.js.org/api/stats/

**Comment by KipOmaha** [comment]
Good idea, I agree. What type of setup? I do testing on dashboards like the one I have setup.

**Comment by KipOmaha** [comment]
Also, I can put u as contributor if you want

**Comment by doriansmiley** [comment]
@KipOmaha do be honest I am not sure yet. I have to learn more about the patterns and optimization techniques. I think most of the stuff related to PRPL pattern will end up effecting Lotus-MVW. But separating the code is pretty critical and Angular's AoT is really cool. Will spend some time this week trying to get caught up and generate a road map for optimization.

**Comment by KipOmaha** [comment]
Thank you @doriansmiley, I really like where your going with your mvw

**Comment by KipOmaha** [comment]
have you looked into yarn for pkg bundling? 
Here is a link to there workflow page. 
https://yarnpkg.com/en/docs/yarn-workflow  ==> I'm not sure if this can work as a bundler.

I'm not sure if this was what you were looking for.

**Comment by KipOmaha** [comment]
I believe Mozilla's Test Pilot Web Page utilizes. At least it did last time I downloaded it and played with the setup it used Yarn.  

It was simple to use!

**Comment by doriansmiley** [comment]
@KipOmaha yep yarn is useful when installing dependencies. It will ensure a flat tree structure. The changes I'm making related to the removal of namespaces from the codebase are the biggest action items for this ticket right now. It will ensure developers load just the modules they need without importing the entire bundle. That helps enable patters like PRPL.
