### ISSUE TITLE
Create CLI for Generating Components From Skins

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#69]
This tool should allow users to defined the following:

1. Import a skin and output a function for the component. 
2. Collection components will be derived from the presence of a collection container and item template.
3. Input params:
    1. The skin path
    2. The component output path
    3. The output path for the test

**Comment by KipOmaha** [comment]
So a form a person can fill out and create a skin part?

**Comment by doriansmiley** [comment]
@KipOmaha so that is what I'm trying to figure out. There are a few of approached:

* A CLI that could take in a JSON manifest which defines the skin parts
* A CLI that prompts the user for the skin part definitions
* A browser based GUI that allows the user to define the skin parts using a form

What would your preference be?

**Comment by KipOmaha** [comment]
I have component's (x-tag) form on my dashboard, at least that was the direction I was going with custom elements.  I just made an updated to it and also added a LotusJS tab.  Here is the link => https://github.com/KipOmaha/x-tag-setup or  
https://kipomaha.github.io/x-tag-setup/index.html  <== Is th GH-Page...  

It's a work in progress

**Comment by doriansmiley** [comment]
@KipOmaha now I get the dashboard concept. So I could totally make something that I could expose as a service that you could use to power this. For example expose a core subclass list, generate the stubs, skin part info, etc. Let me work on an API or this. Really cool.

**Comment by KipOmaha** [comment]
Thanks @doriansmiley

**Comment by doriansmiley** [comment]
YAGNI
