### ISSUE TITLE
Demo using Lotus component classes in Angular 2

### ISSUE THREAD

**Issue by doriansmiley** [doriansmiley/lotusJS#70]
Read: http://www.gistia.com/create-use-custom-components-angular-2/. All we have to do is create a component that extends a lotus base class and implement lifestyle methods to trigger created. The default encapsulation strategy uses shadowDOM.

The goal is to show that because LotusJS component classes have no dependency on a templating engine they are highly reusable in other frameworks. The true test for LotusJS is how easily the components can be migrated to other frameworks. This allows developers to gauge the LOE when moving between frameworks.

Info on how to get the refference to the components element: https://stackoverflow.com/questions/42591822/angular-2-access-an-element-from-the-component-getdocumentbyid-doesnt-work. Note that http://angularjs.blogspot.jp/2016/04/5-rookie-mistakes-to-avoid-with-angular.html recommends not using DOM methods directly but this hurts portability and makes lotus components useless.

Create an Angular component class that extends the LotusJS component class
````
/**
 * Created by dsmiley on 12/4/17.
 */
import { Component } from '@angular/core';
import {Button} from 'lotusjs-components/lib/view/Button';
import { ViewEncapsulation, AfterViewInit, Renderer, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'x-button',
  templateUrl: './Button.html',
  styleUrls: ['./Button.css']
})

export class AngularButton extends Button implements AfterViewInit{

  @ViewChild('button') button:ElementRef;

  constructor(){
    super();
  }

  public ngAfterViewInit():void {
    this.element = this.button.nativeElement;
    this.init();
  }
}
````
 The angular component should also act as a mediator to be sure to show how to access app data and bind it to the component. Also be sure to highlight the fact that when you use lotus component in angular there should never be any use of the templating engine. This ensures there is good encapsulation and that your lotus components remain truly portable.

**Comment by doriansmiley** [comment]
The sample is up on dev under examples/angular and working like a charm. Using lotus components in angular looks really simple!

**Comment by doriansmiley** [comment]
I'd like to enhance this with a data binding example and an application model. This will differ from a normal angular app that creates bindings directly in the view. I believe this i inherently slower than a typical observer pattern, and also bad practice.

**Comment by KipOmaha** [comment]
Are you familiar with liquid layout on Adobe BC?

**Comment by doriansmiley** [comment]
data binding example pushed, worked flawlessly.
