### ISSUE TITLE
Component: Multi-Page Form

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#77]
Multi page Profile form for users that allows them to save the form data offline to a text, json, or xml file than get back to work on the form later.

**Comment by KipOmaha** [comment]
- [ ] Privacy Statement
- [ ] Font Awesome Hooks? -- Or maybe a Adobe Stock that can be monetize alongside FA
- [ ] Skin flex styles with relative and absolute positioning [Two Versions]
- [ ] IndexDB integration for trial periods.

**Comment by KipOmaha** [comment]
@doriansmiley could I get some feedback. I started this lotus component, what do you think?

**Comment by KipOmaha** [comment]
would it be something you'd put up in your sharing space?

**Comment by doriansmiley** [comment]
@KipOmaha take a look at the form component. It might be a good place to start: https://github.com/doriansmiley/lotusJS/tree/dev/example/form

**Comment by KipOmaha** [comment]
IndexedDB library called dexie.js could be utilized for the form component

**Comment by KipOmaha** [comment]
I'm building the component and was wondering why I'm getting the error msg:   

``` SCRIPT5007: Unable to get property 'ComponentMap' of undefined or null reference```

**Comment by doriansmiley** [comment]
So that is telling you that the Lotus namespace is undefined. My guess is the script tags are not importing the required bundles. Did you go through the readme? You have to run npm install and adjust the paths in index.html. The readme should cover the steps.

**Comment by KipOmaha** [comment]
IT IS ALIVE!!!!!
I got the problem corrected

**Comment by doriansmiley** [comment]
nice!

**Comment by KipOmaha** [comment]
Thanks @doriansmiley

**Comment by KipOmaha** [comment]
I've got a new object prototype I've implemented for Dexie.js I have it in typescript but its buggy.
The Javascript version of it based of the compiled typescript I have running though let me know if you want a PR of what I have so far @doriansmiley.

Maybe I can make a pr to a multipage form branch.

**Comment by doriansmiley** [comment]
@KipOmaha can you give me a link to the repo? I don't want a PR as I'm trying to keep the lotus core lean. I may even move all the UI components out into a separate lib to reduce file size. But I'd like to check out the project and see if I can help out.

**Comment by KipOmaha** [comment]
@doriansmiley 
here is a link https://github.com/KipOmaha/online-hobbyshop

**Comment by KipOmaha** [comment]
https://kipomaha.github.io/online-hobbyshop/

**Comment by KipOmaha** [comment]
site example

**Comment by KipOmaha** [comment]
I've got this almost done, but I can't seem to get the `onReady` event to fire in the chrome browser.
