### ISSUE TITLE
inactive of late

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#78]
Is this still a project your interested in @doriansmiley ?

Dan said he was interested in talking about it with you.

**Comment by doriansmiley** [comment]
@KipOmaha yep, I'm just super busy. Working two jobs right now and still trying to update the project.

**Comment by KipOmaha** [comment]
No worries, I'll be lingering around if you have questions on status of x-tag or components.  
I'll try to have some PR's for you and not pester you with questions, lol.

Let me know when you have time to chat on a diff channel.
