### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by KipOmaha** [doriansmiley/lotusJS#84]
This should be prevBtn
```
    Object.defineProperty(AbstractRecordSetCollectionView.prototype, "pervBtn", {
        get: function () {
            return this._pervBtn;
        },
        set: function (value) {
            this._pervBtn = value;
            this.notify(value, 'pervBtn');
        },
        enumerable: true,
        configurable: true
    });
```
I don't believe this is a breaking change. I have it switched for the version of lotus I'm using.

**Comment by KipOmaha** [comment]
I changed all references in `lotus_v0-0-0-a.js`, which is the build I'm using to develop the library further.

**Comment by KipOmaha** [comment]
I'll be making this push soon, @doriansmiley did you want this change?

**Comment by doriansmiley** [comment]
no I'll apply it in the typescript source
