### ISSUE TITLE
Enhancement: Change Math.Random()

### ISSUE THREAD

**Issue by ghost** [doriansmiley/lotusJS#85]
Math.Random() seems like a weak solution for assigning unique id's.  

I suggest using an index system for the AbstractComponent object.

**Comment by KipOmaha** [comment]
I've targeted document.body for the job of storing a unique number index. It's stored as the `data-unique-count` attribute.

**Comment by KipOmaha** [comment]
I may use a different attribute for styling purposes to help out with the shadow dom.

**Comment by KipOmaha** [comment]
What do you think of this solution @all
